package com.example.L3MobileProjet.model;


import com.example.L3MobileProjet.R;

public class DonneePays {

    public static Integer[] drapeaux = {
            R.drawable.albania,
            R.drawable.algeria,
            R.drawable.afghanistan,
            R.drawable.argentina,
            R.drawable.brazil,
            R.drawable.france,
            R.drawable.australia,
            R.drawable.austria,
            R.drawable.belgium,
            R.drawable.bosnia,
            R.drawable.cameroon,
            R.drawable.canada,
            R.drawable.chile,
            R.drawable.china,
            R.drawable.colombia,
            R.drawable.costa_rica,
            R.drawable.ivory_coast,
            R.drawable.croatia,
            R.drawable.czech_republic,
            R.drawable.denmark,
            R.drawable.ecuador,
            R.drawable.egypt,
            R.drawable.finland,
            R.drawable.gabon,
            R.drawable.georgia,
            R.drawable.germany,
            R.drawable.ghana,
            R.drawable.greece,
            R.drawable.ireland,
            R.drawable.iceland,
            R.drawable.india,
            R.drawable.iran,
            R.drawable.israel,
            R.drawable.italy,
            R.drawable.jamaica,
            R.drawable.japan,
            R.drawable.lebanon,
            R.drawable.madagascar,
            R.drawable.mexico,
            R.drawable.morocco,
            R.drawable.netherlands,
            R.drawable.norway,
            R.drawable.philippines,
            R.drawable.poland,
            R.drawable.portugal,
            R.drawable.russian_federation,
            R.drawable.senegal,
            R.drawable.slovakia,
            R.drawable.south_africa,
            R.drawable.spain,
            R.drawable.sweden,
            R.drawable.switzerland,
            R.drawable.syria,
            R.drawable.ukraine,
            R.drawable.united_states_of_america,
            R.drawable.uruguay,
            R.drawable.venezuela,
    };

    public String[] reponses = {
            "Albanie",
            "Algerie",
            "Afghanistan",
            "Argentine",
            "Bresil",
            "France",
            "Australie",
            "Autriche",
            "Belgique",
            "Bosnie",
            "Cameroun",
            "Canada",
            "Chili",
            "Chine",
            "Colombie",
            "Costa Rica",
            "Cote d'ivoire",
            "Croatie",
            "Republique Tcheque",
            "Danemark",
            "Equateur",
            "Egypte",
            "Finlande",
            "Gabon",
            "Georgie",
            "Allemagne",
            "Ghana",
            "Grece",
            "Irelande",
            "Islande",
            "Inde",
            "Iran",
            "Israel",
            "Italie",
            "Jamaïque",
            "Japon",
            "Liban",
            "Madagascar",
            "Mexique",
            "Maroc",
            "Pays Bas",
            "Norvege",
            "Philippines",
            "Pologne",
            "Portugal",
            "Russie",
            "Senegal",
            "Slovaquie",
            "Afrique du sud",
            "Espagne",
            "Suede",
            "Suisse",
            "Syrie",
            "Ukraine",
            "Etats-Unis",
            "Uruguay",
            "Venezuela",
    };
}
